/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedAccessControlRouteImport } from './routes/_authenticated/access-control'
import { Route as AuthenticatedAttendanceRouteImport } from './routes/_authenticated/attendance'
import { Route as AuthenticatedAttendanceAuditRouteImport } from './routes/_authenticated/attendance-audit'
import { Route as AuthenticatedAttendanceCorrectionsRouteImport } from './routes/_authenticated/attendance-corrections'
import { Route as AuthenticatedContractsRouteImport } from './routes/_authenticated/contracts'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDepartmentsRouteImport } from './routes/_authenticated/departments'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedEmployeesRouteImport } from './routes/_authenticated/employees'
import { Route as AuthenticatedEvaluationsRouteImport } from './routes/_authenticated/evaluations'
import { Route as AuthenticatedFinanceRouteImport } from './routes/_authenticated/finance'
import { Route as AuthenticatedHolidaysRouteImport } from './routes/_authenticated/holidays'
import { Route as AuthenticatedImportsRouteImport } from './routes/_authenticated/imports'
import { Route as AuthenticatedLeavesRouteImport } from './routes/_authenticated/leaves'
import { Route as AuthenticatedMeRouteImport } from './routes/_authenticated/me'
import { Route as AuthenticatedMyTeamRouteImport } from './routes/_authenticated/my-team'
import { Route as AuthenticatedPayrollRouteImport } from './routes/_authenticated/payroll'
import { Route as AuthenticatedPayrollAuditRouteImport } from './routes/_authenticated/payroll-audit'
import { Route as AuthenticatedPayrollDisputesRouteImport } from './routes/_authenticated/payroll-disputes'
import { Route as AuthenticatedPermissionsRouteImport } from './routes/_authenticated/permissions'
import { Route as AuthenticatedRolesRouteImport } from './routes/_authenticated/roles'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedShiftsRouteImport } from './routes/_authenticated/shifts'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AuthenticatedContractsNewRouteImport } from './routes/_authenticated/contracts.new'
import { Route as AuthenticatedEmployeesEmployeeIdRouteImport } from './routes/_authenticated/employees.$employeeId'
import { Route as AuthenticatedPayslipIdRouteImport } from './routes/_authenticated/payslip.$id'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as AuthenticatedContractsContractIdAuditRouteImport } from './routes/_authenticated/contracts.$contractId.audit'
import { Route as AuthenticatedContractsContractIdStatusRouteImport } from './routes/_authenticated/contracts.$contractId.status'
import { Route as ApiPublicHooksAttendanceRemindersRouteImport } from './routes/api/public/hooks/attendance-reminders'
import { Route as ApiPublicHooksMonthlyPayrollRouteImport } from './routes/api/public/hooks/monthly-payroll'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAccessControlRoute =
  AuthenticatedAccessControlRouteImport.update({
    id: '/access-control',
    path: '/access-control',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAttendanceRoute = AuthenticatedAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAttendanceAuditRoute =
  AuthenticatedAttendanceAuditRouteImport.update({
    id: '/attendance-audit',
    path: '/attendance-audit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAttendanceCorrectionsRoute =
  AuthenticatedAttendanceCorrectionsRouteImport.update({
    id: '/attendance-corrections',
    path: '/attendance-corrections',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContractsRoute = AuthenticatedContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDepartmentsRoute =
  AuthenticatedDepartmentsRouteImport.update({
    id: '/departments',
    path: '/departments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmployeesRoute = AuthenticatedEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEvaluationsRoute =
  AuthenticatedEvaluationsRouteImport.update({
    id: '/evaluations',
    path: '/evaluations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceRoute = AuthenticatedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHolidaysRoute = AuthenticatedHolidaysRouteImport.update({
  id: '/holidays',
  path: '/holidays',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImportsRoute = AuthenticatedImportsRouteImport.update({
  id: '/imports',
  path: '/imports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeavesRoute = AuthenticatedLeavesRouteImport.update({
  id: '/leaves',
  path: '/leaves',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeRoute = AuthenticatedMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyTeamRoute = AuthenticatedMyTeamRouteImport.update({
  id: '/my-team',
  path: '/my-team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPayrollRoute = AuthenticatedPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPayrollAuditRoute =
  AuthenticatedPayrollAuditRouteImport.update({
    id: '/payroll-audit',
    path: '/payroll-audit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPayrollDisputesRoute =
  AuthenticatedPayrollDisputesRouteImport.update({
    id: '/payroll-disputes',
    path: '/payroll-disputes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPermissionsRoute =
  AuthenticatedPermissionsRouteImport.update({
    id: '/permissions',
    path: '/permissions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRolesRoute = AuthenticatedRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedShiftsRoute = AuthenticatedShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedContractsNewRoute =
  AuthenticatedContractsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedContractsRoute,
  } as any)
const AuthenticatedEmployeesEmployeeIdRoute =
  AuthenticatedEmployeesEmployeeIdRouteImport.update({
    id: '/$employeeId',
    path: '/$employeeId',
    getParentRoute: () => AuthenticatedEmployeesRoute,
  } as any)
const AuthenticatedPayslipIdRoute = AuthenticatedPayslipIdRouteImport.update({
  id: '/payslip/$id',
  path: '/payslip/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedContractsContractIdAuditRoute =
  AuthenticatedContractsContractIdAuditRouteImport.update({
    id: '/$contractId/audit',
    path: '/$contractId/audit',
    getParentRoute: () => AuthenticatedContractsRoute,
  } as any)
const AuthenticatedContractsContractIdStatusRoute =
  AuthenticatedContractsContractIdStatusRouteImport.update({
    id: '/$contractId/status',
    path: '/$contractId/status',
    getParentRoute: () => AuthenticatedContractsRoute,
  } as any)
const ApiPublicHooksAttendanceRemindersRoute =
  ApiPublicHooksAttendanceRemindersRouteImport.update({
    id: '/api/public/hooks/attendance-reminders',
    path: '/api/public/hooks/attendance-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksMonthlyPayrollRoute =
  ApiPublicHooksMonthlyPayrollRouteImport.update({
    id: '/api/public/hooks/monthly-payroll',
    path: '/api/public/hooks/monthly-payroll',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/access-control': typeof AuthenticatedAccessControlRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/attendance-audit': typeof AuthenticatedAttendanceAuditRoute
  '/attendance-corrections': typeof AuthenticatedAttendanceCorrectionsRoute
  '/contracts': typeof AuthenticatedContractsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/departments': typeof AuthenticatedDepartmentsRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/employees': typeof AuthenticatedEmployeesRouteWithChildren
  '/evaluations': typeof AuthenticatedEvaluationsRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/holidays': typeof AuthenticatedHolidaysRoute
  '/imports': typeof AuthenticatedImportsRoute
  '/leaves': typeof AuthenticatedLeavesRoute
  '/me': typeof AuthenticatedMeRoute
  '/my-team': typeof AuthenticatedMyTeamRoute
  '/payroll': typeof AuthenticatedPayrollRoute
  '/payroll-audit': typeof AuthenticatedPayrollAuditRoute
  '/payroll-disputes': typeof AuthenticatedPayrollDisputesRoute
  '/permissions': typeof AuthenticatedPermissionsRoute
  '/roles': typeof AuthenticatedRolesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/shifts': typeof AuthenticatedShiftsRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/contracts/new': typeof AuthenticatedContractsNewRoute
  '/employees/$employeeId': typeof AuthenticatedEmployeesEmployeeIdRoute
  '/payslip/$id': typeof AuthenticatedPayslipIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/contracts/$contractId/audit': typeof AuthenticatedContractsContractIdAuditRoute
  '/contracts/$contractId/status': typeof AuthenticatedContractsContractIdStatusRoute
  '/api/public/hooks/attendance-reminders': typeof ApiPublicHooksAttendanceRemindersRoute
  '/api/public/hooks/monthly-payroll': typeof ApiPublicHooksMonthlyPayrollRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/access-control': typeof AuthenticatedAccessControlRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/attendance-audit': typeof AuthenticatedAttendanceAuditRoute
  '/attendance-corrections': typeof AuthenticatedAttendanceCorrectionsRoute
  '/contracts': typeof AuthenticatedContractsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/departments': typeof AuthenticatedDepartmentsRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/employees': typeof AuthenticatedEmployeesRouteWithChildren
  '/evaluations': typeof AuthenticatedEvaluationsRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/holidays': typeof AuthenticatedHolidaysRoute
  '/imports': typeof AuthenticatedImportsRoute
  '/leaves': typeof AuthenticatedLeavesRoute
  '/me': typeof AuthenticatedMeRoute
  '/my-team': typeof AuthenticatedMyTeamRoute
  '/payroll': typeof AuthenticatedPayrollRoute
  '/payroll-audit': typeof AuthenticatedPayrollAuditRoute
  '/payroll-disputes': typeof AuthenticatedPayrollDisputesRoute
  '/permissions': typeof AuthenticatedPermissionsRoute
  '/roles': typeof AuthenticatedRolesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/shifts': typeof AuthenticatedShiftsRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/contracts/new': typeof AuthenticatedContractsNewRoute
  '/employees/$employeeId': typeof AuthenticatedEmployeesEmployeeIdRoute
  '/payslip/$id': typeof AuthenticatedPayslipIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/contracts/$contractId/audit': typeof AuthenticatedContractsContractIdAuditRoute
  '/contracts/$contractId/status': typeof AuthenticatedContractsContractIdStatusRoute
  '/api/public/hooks/attendance-reminders': typeof ApiPublicHooksAttendanceRemindersRoute
  '/api/public/hooks/monthly-payroll': typeof ApiPublicHooksMonthlyPayrollRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/access-control': typeof AuthenticatedAccessControlRoute
  '/_authenticated/attendance': typeof AuthenticatedAttendanceRoute
  '/_authenticated/attendance-audit': typeof AuthenticatedAttendanceAuditRoute
  '/_authenticated/attendance-corrections': typeof AuthenticatedAttendanceCorrectionsRoute
  '/_authenticated/contracts': typeof AuthenticatedContractsRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/departments': typeof AuthenticatedDepartmentsRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/employees': typeof AuthenticatedEmployeesRouteWithChildren
  '/_authenticated/evaluations': typeof AuthenticatedEvaluationsRoute
  '/_authenticated/finance': typeof AuthenticatedFinanceRoute
  '/_authenticated/holidays': typeof AuthenticatedHolidaysRoute
  '/_authenticated/imports': typeof AuthenticatedImportsRoute
  '/_authenticated/leaves': typeof AuthenticatedLeavesRoute
  '/_authenticated/me': typeof AuthenticatedMeRoute
  '/_authenticated/my-team': typeof AuthenticatedMyTeamRoute
  '/_authenticated/payroll': typeof AuthenticatedPayrollRoute
  '/_authenticated/payroll-audit': typeof AuthenticatedPayrollAuditRoute
  '/_authenticated/payroll-disputes': typeof AuthenticatedPayrollDisputesRoute
  '/_authenticated/permissions': typeof AuthenticatedPermissionsRoute
  '/_authenticated/roles': typeof AuthenticatedRolesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/shifts': typeof AuthenticatedShiftsRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/contracts/new': typeof AuthenticatedContractsNewRoute
  '/_authenticated/employees/$employeeId': typeof AuthenticatedEmployeesEmployeeIdRoute
  '/_authenticated/payslip/$id': typeof AuthenticatedPayslipIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/_authenticated/contracts/$contractId/audit': typeof AuthenticatedContractsContractIdAuditRoute
  '/_authenticated/contracts/$contractId/status': typeof AuthenticatedContractsContractIdStatusRoute
  '/api/public/hooks/attendance-reminders': typeof ApiPublicHooksAttendanceRemindersRoute
  '/api/public/hooks/monthly-payroll': typeof ApiPublicHooksMonthlyPayrollRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/access-control'
    | '/attendance'
    | '/attendance-audit'
    | '/attendance-corrections'
    | '/contracts'
    | '/dashboard'
    | '/departments'
    | '/documents'
    | '/employees'
    | '/evaluations'
    | '/finance'
    | '/holidays'
    | '/imports'
    | '/leaves'
    | '/me'
    | '/my-team'
    | '/payroll'
    | '/payroll-audit'
    | '/payroll-disputes'
    | '/permissions'
    | '/roles'
    | '/settings'
    | '/shifts'
    | '/email/unsubscribe'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/contracts/new'
    | '/employees/$employeeId'
    | '/payslip/$id'
    | '/lovable/email/suppression'
    | '/contracts/$contractId/audit'
    | '/contracts/$contractId/status'
    | '/api/public/hooks/attendance-reminders'
    | '/api/public/hooks/monthly-payroll'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/access-control'
    | '/attendance'
    | '/attendance-audit'
    | '/attendance-corrections'
    | '/contracts'
    | '/dashboard'
    | '/departments'
    | '/documents'
    | '/employees'
    | '/evaluations'
    | '/finance'
    | '/holidays'
    | '/imports'
    | '/leaves'
    | '/me'
    | '/my-team'
    | '/payroll'
    | '/payroll-audit'
    | '/payroll-disputes'
    | '/permissions'
    | '/roles'
    | '/settings'
    | '/shifts'
    | '/email/unsubscribe'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/contracts/new'
    | '/employees/$employeeId'
    | '/payslip/$id'
    | '/lovable/email/suppression'
    | '/contracts/$contractId/audit'
    | '/contracts/$contractId/status'
    | '/api/public/hooks/attendance-reminders'
    | '/api/public/hooks/monthly-payroll'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mcp'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/access-control'
    | '/_authenticated/attendance'
    | '/_authenticated/attendance-audit'
    | '/_authenticated/attendance-corrections'
    | '/_authenticated/contracts'
    | '/_authenticated/dashboard'
    | '/_authenticated/departments'
    | '/_authenticated/documents'
    | '/_authenticated/employees'
    | '/_authenticated/evaluations'
    | '/_authenticated/finance'
    | '/_authenticated/holidays'
    | '/_authenticated/imports'
    | '/_authenticated/leaves'
    | '/_authenticated/me'
    | '/_authenticated/my-team'
    | '/_authenticated/payroll'
    | '/_authenticated/payroll-audit'
    | '/_authenticated/payroll-disputes'
    | '/_authenticated/permissions'
    | '/_authenticated/roles'
    | '/_authenticated/settings'
    | '/_authenticated/shifts'
    | '/email/unsubscribe'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/contracts/new'
    | '/_authenticated/employees/$employeeId'
    | '/_authenticated/payslip/$id'
    | '/lovable/email/suppression'
    | '/_authenticated/contracts/$contractId/audit'
    | '/_authenticated/contracts/$contractId/status'
    | '/api/public/hooks/attendance-reminders'
    | '/api/public/hooks/monthly-payroll'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicHooksAttendanceRemindersRoute: typeof ApiPublicHooksAttendanceRemindersRoute
  ApiPublicHooksMonthlyPayrollRoute: typeof ApiPublicHooksMonthlyPayrollRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/access-control': {
      id: '/_authenticated/access-control'
      path: '/access-control'
      fullPath: '/access-control'
      preLoaderRoute: typeof AuthenticatedAccessControlRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance': {
      id: '/_authenticated/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthenticatedAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance-audit': {
      id: '/_authenticated/attendance-audit'
      path: '/attendance-audit'
      fullPath: '/attendance-audit'
      preLoaderRoute: typeof AuthenticatedAttendanceAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance-corrections': {
      id: '/_authenticated/attendance-corrections'
      path: '/attendance-corrections'
      fullPath: '/attendance-corrections'
      preLoaderRoute: typeof AuthenticatedAttendanceCorrectionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contracts': {
      id: '/_authenticated/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof AuthenticatedContractsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/departments': {
      id: '/_authenticated/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof AuthenticatedDepartmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employees': {
      id: '/_authenticated/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AuthenticatedEmployeesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/evaluations': {
      id: '/_authenticated/evaluations'
      path: '/evaluations'
      fullPath: '/evaluations'
      preLoaderRoute: typeof AuthenticatedEvaluationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance': {
      id: '/_authenticated/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedFinanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/holidays': {
      id: '/_authenticated/holidays'
      path: '/holidays'
      fullPath: '/holidays'
      preLoaderRoute: typeof AuthenticatedHolidaysRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/imports': {
      id: '/_authenticated/imports'
      path: '/imports'
      fullPath: '/imports'
      preLoaderRoute: typeof AuthenticatedImportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leaves': {
      id: '/_authenticated/leaves'
      path: '/leaves'
      fullPath: '/leaves'
      preLoaderRoute: typeof AuthenticatedLeavesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/me': {
      id: '/_authenticated/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AuthenticatedMeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-team': {
      id: '/_authenticated/my-team'
      path: '/my-team'
      fullPath: '/my-team'
      preLoaderRoute: typeof AuthenticatedMyTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payroll': {
      id: '/_authenticated/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof AuthenticatedPayrollRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payroll-audit': {
      id: '/_authenticated/payroll-audit'
      path: '/payroll-audit'
      fullPath: '/payroll-audit'
      preLoaderRoute: typeof AuthenticatedPayrollAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payroll-disputes': {
      id: '/_authenticated/payroll-disputes'
      path: '/payroll-disputes'
      fullPath: '/payroll-disputes'
      preLoaderRoute: typeof AuthenticatedPayrollDisputesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/permissions': {
      id: '/_authenticated/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof AuthenticatedPermissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roles': {
      id: '/_authenticated/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AuthenticatedRolesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shifts': {
      id: '/_authenticated/shifts'
      path: '/shifts'
      fullPath: '/shifts'
      preLoaderRoute: typeof AuthenticatedShiftsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/contracts/new': {
      id: '/_authenticated/contracts/new'
      path: '/new'
      fullPath: '/contracts/new'
      preLoaderRoute: typeof AuthenticatedContractsNewRouteImport
      parentRoute: typeof AuthenticatedContractsRoute
    }
    '/_authenticated/employees/$employeeId': {
      id: '/_authenticated/employees/$employeeId'
      path: '/$employeeId'
      fullPath: '/employees/$employeeId'
      preLoaderRoute: typeof AuthenticatedEmployeesEmployeeIdRouteImport
      parentRoute: typeof AuthenticatedEmployeesRoute
    }
    '/_authenticated/payslip/$id': {
      id: '/_authenticated/payslip/$id'
      path: '/payslip/$id'
      fullPath: '/payslip/$id'
      preLoaderRoute: typeof AuthenticatedPayslipIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/contracts/$contractId/audit': {
      id: '/_authenticated/contracts/$contractId/audit'
      path: '/$contractId/audit'
      fullPath: '/contracts/$contractId/audit'
      preLoaderRoute: typeof AuthenticatedContractsContractIdAuditRouteImport
      parentRoute: typeof AuthenticatedContractsRoute
    }
    '/_authenticated/contracts/$contractId/status': {
      id: '/_authenticated/contracts/$contractId/status'
      path: '/$contractId/status'
      fullPath: '/contracts/$contractId/status'
      preLoaderRoute: typeof AuthenticatedContractsContractIdStatusRouteImport
      parentRoute: typeof AuthenticatedContractsRoute
    }
    '/api/public/hooks/attendance-reminders': {
      id: '/api/public/hooks/attendance-reminders'
      path: '/api/public/hooks/attendance-reminders'
      fullPath: '/api/public/hooks/attendance-reminders'
      preLoaderRoute: typeof ApiPublicHooksAttendanceRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/monthly-payroll': {
      id: '/api/public/hooks/monthly-payroll'
      path: '/api/public/hooks/monthly-payroll'
      fullPath: '/api/public/hooks/monthly-payroll'
      preLoaderRoute: typeof ApiPublicHooksMonthlyPayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedContractsRouteChildren {
  AuthenticatedContractsNewRoute: typeof AuthenticatedContractsNewRoute
  AuthenticatedContractsContractIdAuditRoute: typeof AuthenticatedContractsContractIdAuditRoute
  AuthenticatedContractsContractIdStatusRoute: typeof AuthenticatedContractsContractIdStatusRoute
}

const AuthenticatedContractsRouteChildren: AuthenticatedContractsRouteChildren =
  {
    AuthenticatedContractsNewRoute: AuthenticatedContractsNewRoute,
    AuthenticatedContractsContractIdAuditRoute:
      AuthenticatedContractsContractIdAuditRoute,
    AuthenticatedContractsContractIdStatusRoute:
      AuthenticatedContractsContractIdStatusRoute,
  }

const AuthenticatedContractsRouteWithChildren =
  AuthenticatedContractsRoute._addFileChildren(
    AuthenticatedContractsRouteChildren,
  )

interface AuthenticatedEmployeesRouteChildren {
  AuthenticatedEmployeesEmployeeIdRoute: typeof AuthenticatedEmployeesEmployeeIdRoute
}

const AuthenticatedEmployeesRouteChildren: AuthenticatedEmployeesRouteChildren =
  {
    AuthenticatedEmployeesEmployeeIdRoute:
      AuthenticatedEmployeesEmployeeIdRoute,
  }

const AuthenticatedEmployeesRouteWithChildren =
  AuthenticatedEmployeesRoute._addFileChildren(
    AuthenticatedEmployeesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccessControlRoute: typeof AuthenticatedAccessControlRoute
  AuthenticatedAttendanceRoute: typeof AuthenticatedAttendanceRoute
  AuthenticatedAttendanceAuditRoute: typeof AuthenticatedAttendanceAuditRoute
  AuthenticatedAttendanceCorrectionsRoute: typeof AuthenticatedAttendanceCorrectionsRoute
  AuthenticatedContractsRoute: typeof AuthenticatedContractsRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDepartmentsRoute: typeof AuthenticatedDepartmentsRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedEmployeesRoute: typeof AuthenticatedEmployeesRouteWithChildren
  AuthenticatedEvaluationsRoute: typeof AuthenticatedEvaluationsRoute
  AuthenticatedFinanceRoute: typeof AuthenticatedFinanceRoute
  AuthenticatedHolidaysRoute: typeof AuthenticatedHolidaysRoute
  AuthenticatedImportsRoute: typeof AuthenticatedImportsRoute
  AuthenticatedLeavesRoute: typeof AuthenticatedLeavesRoute
  AuthenticatedMeRoute: typeof AuthenticatedMeRoute
  AuthenticatedMyTeamRoute: typeof AuthenticatedMyTeamRoute
  AuthenticatedPayrollRoute: typeof AuthenticatedPayrollRoute
  AuthenticatedPayrollAuditRoute: typeof AuthenticatedPayrollAuditRoute
  AuthenticatedPayrollDisputesRoute: typeof AuthenticatedPayrollDisputesRoute
  AuthenticatedPermissionsRoute: typeof AuthenticatedPermissionsRoute
  AuthenticatedRolesRoute: typeof AuthenticatedRolesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedShiftsRoute: typeof AuthenticatedShiftsRoute
  AuthenticatedPayslipIdRoute: typeof AuthenticatedPayslipIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccessControlRoute: AuthenticatedAccessControlRoute,
  AuthenticatedAttendanceRoute: AuthenticatedAttendanceRoute,
  AuthenticatedAttendanceAuditRoute: AuthenticatedAttendanceAuditRoute,
  AuthenticatedAttendanceCorrectionsRoute:
    AuthenticatedAttendanceCorrectionsRoute,
  AuthenticatedContractsRoute: AuthenticatedContractsRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDepartmentsRoute: AuthenticatedDepartmentsRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedEmployeesRoute: AuthenticatedEmployeesRouteWithChildren,
  AuthenticatedEvaluationsRoute: AuthenticatedEvaluationsRoute,
  AuthenticatedFinanceRoute: AuthenticatedFinanceRoute,
  AuthenticatedHolidaysRoute: AuthenticatedHolidaysRoute,
  AuthenticatedImportsRoute: AuthenticatedImportsRoute,
  AuthenticatedLeavesRoute: AuthenticatedLeavesRoute,
  AuthenticatedMeRoute: AuthenticatedMeRoute,
  AuthenticatedMyTeamRoute: AuthenticatedMyTeamRoute,
  AuthenticatedPayrollRoute: AuthenticatedPayrollRoute,
  AuthenticatedPayrollAuditRoute: AuthenticatedPayrollAuditRoute,
  AuthenticatedPayrollDisputesRoute: AuthenticatedPayrollDisputesRoute,
  AuthenticatedPermissionsRoute: AuthenticatedPermissionsRoute,
  AuthenticatedRolesRoute: AuthenticatedRolesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedShiftsRoute: AuthenticatedShiftsRoute,
  AuthenticatedPayslipIdRoute: AuthenticatedPayslipIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicHooksAttendanceRemindersRoute:
    ApiPublicHooksAttendanceRemindersRoute,
  ApiPublicHooksMonthlyPayrollRoute: ApiPublicHooksMonthlyPayrollRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
